modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "kubejsadditions"
version = "${version}"
displayName = "KubeJS Additons (Forge)"
authors = "ILIKEPIEFOO2"
description = '''
A mod that serves as a bunch of additional features to KubeJS.
'''
#logoFile = ""

[[dependencies.kubejsadditions]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsadditions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsadditions]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.82,)"
ordering = "AFTER"
side = "BOTH"