modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "${mod_issues}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
displayURL = "${mod_homepage}"
version = "${mod_version}"
displayName = "${mod_name} (Forge)"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "${mod_icon}"

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.82,)"
ordering = "AFTER"
side = "BOTH"