org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
group=pie.ilikepiefoo
modId=kubejsadditions
modName=KubeJS Additions
modVersion=6.0.0
minecraftVersion=1.21.1
modDescription=A mod that adds a bunch of additional features to KubeJS.
modAuthor=ILIKEPIEFOO2
modLicense=All Rights Reserved
modHomepage=https://legacy.curseforge.com/minecraft/mc-mods/kubejs-additions
modIssues=https://github.com/Hunter19823/kubejsadditions/issues
modIcon=kubejsadditions/kubejs_logo.png
neoforgeVersion=21.1.31
neoforgeVersions=[21.1.31,)
kubejsVersion=2101.7.1-build.192
architecturyVersion=13.0.6
jeiVersion=19.14.1.143
jadeVersion=15.10.5+neoforge
jadeFileId=7545219
supportedVersions=1.21.1, 1.21
curseforge_id=594387
modrinth_id=BZemjxZb
uploadType=release
